// Стили прежнего дизайна (0.14.0) — только то, что в новом стало иначе.
// Собрано сравнением двух объектов styles, руками не правится: если меняется
// новый дизайн, прежний остаётся как был.
export const CLASSIC_STYLES = {
  shell: {"display":"flex","minHeight":"100vh","background":"var(--bg)","color":"var(--ink)","position":"relative"},
  main: {"flex":1,"minWidth":0,"padding":"24px 26px 40px","maxWidth":1400},
  grid2: {"display":"grid","gridTemplateColumns":"repeat(auto-fit, minmax(min(340px, 100%), 1fr))","gap":"0 16px"},
  cardTitle: {"fontFamily":"'PT Serif', Georgia, serif","fontSize":19,"marginBottom":5},
  todayRow: {"display":"flex","alignItems":"baseline","gap":8,"flexWrap":"wrap","borderLeft":"4px solid","borderRadius":"0 4px 4px 0","padding":"6px 9px"},
  reviewRow: {"display":"flex","alignItems":"center","gap":9,"border":"1px solid var(--line2)","background":"var(--panel2)","borderRadius":9,"padding":"8px 11px"},
  reviewBtn: {"flexShrink":0,"border":"1px solid var(--line)","background":"var(--panel)","color":"var(--ink2)","borderRadius":8,"padding":"6px 11px","fontSize":12.5,"fontWeight":600},
  searchRow: {"display":"flex","alignItems":"flex-start","gap":9,"width":"100%","textAlign":"left","border":"1px solid var(--line2)","background":"var(--panel2)","borderRadius":9,"padding":"9px 11px","marginBottom":5},
  nowMark: {"borderLeft":"4px solid","borderRadius":"0 4px 4px 0","padding":"5px 9px"},
  weekStrip: {"display":"flex","alignItems":"center","gap":12,"flexWrap":"wrap","padding":"10px 14px","marginBottom":16,"borderRadius":12,"border":"1px solid var(--accent)","background":"var(--panel)"},
  weekStripText: {"fontSize":13.5,"color":"var(--ink3)","flex":"1 1 220px","minWidth":0},
  weekGo: {"border":"none","color":"var(--btnInk)","background":"var(--btnBg)","borderRadius":9,"padding":"8px 15px","fontSize":13,"fontWeight":600},
  weekSkip: {"border":"1px solid var(--line)","background":"var(--panel2)","color":"var(--ink2)","borderRadius":9,"padding":"8px 15px","fontSize":13,"fontWeight":600},
  pulseWarm: {"background":"var(--warmBg)","border":"1px solid var(--warmLine)","color":"var(--warmInk)","borderRadius":9,"padding":"8px 10px"},
  notebookSelect: {"flex":"1 1 160px","minWidth":0,"padding":"7px 9px","border":"1px solid var(--line)","borderRadius":8,"fontSize":13.5,"fontWeight":600,"background":"var(--panel2)","color":"var(--ink)"},
  page: {"fontFamily":"Inter, system-ui, sans-serif","background":"var(--bg)","color":"var(--ink)","minHeight":"100vh","padding":"28px 20px 60px","maxWidth":880,"margin":"0 auto"},
  dateInput: {"border":"1px solid var(--line)","background":"var(--panel2)","color":"inherit","borderRadius":8,"padding":"7px 9px","fontSize":12.5,"width":"100%"},
  calendarLinkInput: {"width":"100%","padding":"5px 8px","border":"1px solid var(--line)","borderRadius":8,"fontSize":11.5,"background":"var(--panel2)","color":"var(--ink2)"},
  subscribeLink: {"display":"inline-block","border":"none","color":"var(--btnInk)","background":"var(--btnBg)","borderRadius":8,"padding":"5px 10px","fontSize":12,"fontWeight":600,"textDecoration":"none"},
  subscribeLinkSecondary: {"display":"inline-block","border":"1px solid var(--line)","background":"var(--panel2)","borderRadius":8,"padding":"5px 10px","fontSize":12,"fontWeight":600,"color":"var(--ink)","textDecoration":"none"},
  secondaryBtnSmall: {"border":"1px solid var(--line)","background":"var(--panel2)","borderRadius":8,"padding":"5px 10px","fontSize":12,"fontWeight":600,"color":"var(--ink)"},
  eventEditRow: {"display":"flex","alignItems":"flex-start","gap":8,"flexWrap":"wrap","marginBottom":8,"borderLeft":"4px solid","borderRadius":"0 9px 9px 0","padding":"10px 12px"},
  eventDaysWord: {"fontFamily":"Inter, system-ui, sans-serif","fontSize":10.5,"fontWeight":600,"opacity":0.85,"marginTop":2},
  eventNameInput: {"flex":"3 1 200px","minWidth":0,"padding":"7px 10px","border":"1px solid var(--line)","borderRadius":8,"fontSize":13,"background":"var(--panel2)"},
  eventDateInput: {"padding":"5px 6px","border":"1px solid var(--line)","borderRadius":8,"fontSize":12.5,"background":"var(--panel2)"},
  priorityBtn: {"border":"1px solid","borderRadius":8,"padding":"4px 7px","fontSize":12,"fontWeight":700,"lineHeight":1.1},
  tabBtn: {"border":"1px solid","borderRadius":8,"padding":"4px 12px","fontSize":12.5,"fontWeight":600},
  foldCard: {"border":"1px solid var(--line)","background":"var(--panel2)","borderRadius":11,"padding":"10px 14px","marginBottom":12},
  sundayBtn: {"border":"1px solid var(--line)","background":"var(--panel2)","borderRadius":8,"padding":"5px 12px","fontSize":12.5,"fontWeight":600,"color":"var(--ink2)"},
  undoCancel: {"border":"1px solid var(--railInk2)","background":"transparent","color":"var(--railInk)","borderRadius":8,"padding":"4px 10px","fontSize":13},
  undoConfirm: {"border":"none","background":"var(--green)","color":"#fff","borderRadius":8,"padding":"4px 10px","fontSize":13},
  levelChip: {"border":"1px solid","borderRadius":7,"fontSize":10,"fontWeight":600,"padding":"1px 5px","marginLeft":6,"verticalAlign":"middle"},
  fromScheduleBadge: {"fontSize":10.5,"color":"var(--red)","border":"1px solid var(--redLine)","borderRadius":8,"padding":"1px 6px"},
  pastClear: {"border":"1px solid var(--line)","background":"var(--panel2)","color":"var(--ink3)","borderRadius":8,"padding":"4px 10px","fontSize":11.5},
  card: {"background":"var(--panel)","border":"1px solid var(--line)","borderRadius":12,"padding":"18px 20px","marginBottom":16},
  dailyGoalInput: {"width":"100%","padding":"4px 3px","border":"1px solid var(--line)","borderRadius":8,"fontSize":13,"textAlign":"center","background":"var(--panel2)"},
  smallNumInput: {"width":52,"padding":"7px 9px","border":"1px solid var(--line)","borderRadius":8,"fontSize":13,"background":"var(--panel2)"},
  capacityBox: {"border":"1px solid","borderRadius":9,"padding":"12px 14px","fontSize":13.5,"lineHeight":1.9,"background":"var(--panel2)"},
  skewWarning: {"marginTop":10,"padding":"10px 14px","background":"var(--redBg)","border":"1px solid var(--redLine)","borderRadius":9,"fontSize":13.5,"color":"var(--red)","fontWeight":600},
  select: {"padding":"8px 10px","border":"1px solid var(--line)","borderRadius":8,"fontSize":13,"background":"var(--panel2)"},
  subjCard: {"background":"var(--panel2)","border":"1px solid","borderRadius":11,"padding":"16px 18px","transition":"transform 0.15s ease","containerType":"inline-size"},
  addSubjectInput: {"flex":"1 1 240px","padding":"7px 10px","border":"1px solid var(--line)","borderRadius":8,"fontSize":13.5,"background":"var(--panel2)"},
  scheduleDayBlock: {"background":"var(--panel2)","border":"1px solid var(--line)","borderRadius":11,"padding":"14px 16px"},
  lessonTaskInput: {"flex":"1 1 180px","minWidth":0,"border":"1px solid var(--line)","background":"var(--panel2)","borderRadius":8,"padding":"6px 9px","fontSize":12.5,"resize":"none"},
  lessonTaskMinutes: {"width":62,"border":"1px solid var(--line)","background":"var(--panel2)","borderRadius":8,"padding":"6px 8px","fontSize":12.5},
  scheduleEntry: {"display":"flex","flexDirection":"column","gap":4,"borderLeft":"5px solid","borderRadius":"0 4px 4px 0","padding":"6px 8px","marginBottom":8},
  rowDone: {"border":"none","color":"var(--btnInk)","background":"var(--btnBg)","borderRadius":8,"padding":"5px 12px","fontSize":12,"fontWeight":600},
  examForm: {"display":"flex","flexDirection":"column","gap":6,"padding":"8px 8px 10px","marginBottom":8,"border":"1px dashed var(--gold)","borderRadius":9,"background":"var(--warmBg)"},
  examKindOn: {"border":"1px solid var(--redStrong)","background":"var(--redStrong)","color":"var(--btnInk)","borderRadius":8,"padding":"2px 8px","fontSize":11,"fontWeight":700,"letterSpacing":0.3,"textTransform":"uppercase"},
  examKindOff: {"border":"1px solid var(--line)","background":"var(--panel)","color":"var(--mute)","borderRadius":8,"padding":"2px 8px","fontSize":11,"fontWeight":600,"letterSpacing":0.3,"textTransform":"uppercase"},
  examDateInput: {"padding":"5px 7px","border":"1px solid var(--line)","borderRadius":8,"fontSize":12,"background":"var(--panel2)"},
  scheduleSelect: {"padding":"7px 9px","border":"1px solid var(--line)","borderRadius":8,"fontSize":12.5,"background":"var(--panel2)","width":"100%"},
  scheduleSubjectInput: {"flex":"1 1 120px","minWidth":0,"padding":"4px 6px","border":"1px solid var(--line)","borderRadius":8,"fontSize":12.5,"background":"var(--panel2)","fontWeight":600},
  scheduleTimeInput: {"padding":"5px 6px","border":"1px solid var(--line)","borderRadius":8,"fontSize":12,"background":"var(--panel2)","width":82},
  scheduleRoomInput: {"padding":"7px 9px","border":"1px solid var(--line)","borderRadius":8,"fontSize":12.5,"background":"var(--panel2)"},
  scheduleTeacherInput: {"padding":"7px 9px","border":"1px solid var(--line)","borderRadius":8,"fontSize":12.5,"background":"var(--panel2)"},
  topicRow: {"display":"flex","alignItems":"center","gap":8,"fontSize":13.5,"padding":"8px 10px","borderRadius":9,"border":"1px solid transparent","flexWrap":"wrap"},
  durationInput: {"width":44,"padding":"5px 7px","border":"1px solid var(--line)","borderRadius":8,"fontSize":12,"background":"var(--panel2)"},
  notesToggle: {"background":"none","border":"1px solid var(--line)","borderRadius":8,"fontSize":11.5,"padding":"3px 7px","color":"var(--ink2)"},
  colorPick: {"width":24,"height":20,"padding":0,"border":"1px solid var(--line)","borderRadius":7,"background":"var(--panel2)","flexShrink":0},
  noteInput: {"flex":"1 1 180px","padding":"7px 10px","border":"1px solid var(--line)","borderRadius":8,"fontSize":12.5,"background":"var(--panel2)"},
  addBtnSmall: {"border":"none","color":"var(--btnInk)","background":"var(--btnBg)","borderRadius":8,"padding":"5px 10px","fontSize":12,"fontWeight":600},
  addTopicInput: {"flex":1,"padding":"7px 10px","border":"1px solid var(--line)","borderRadius":8,"fontSize":13,"background":"var(--panel2)"},
  addTopicUrlInput: {"flex":"1 1 160px","padding":"7px 10px","border":"1px solid var(--line)","borderRadius":8,"fontSize":13,"background":"var(--panel2)"},
  addBtn: {"border":"none","color":"var(--btnInk)","background":"var(--btnBg)","borderRadius":8,"padding":"6px 12px","fontSize":13,"fontWeight":600},
  calNavBtn: {"background":"none","border":"1px solid var(--line)","borderRadius":8,"width":28,"height":28,"fontSize":15,"color":"var(--ink)"},
  calCell: {"position":"relative","aspectRatio":"1","border":"none","borderRadius":8,"fontSize":12.5,"fontWeight":600,"display":"flex","alignItems":"center","justifyContent":"center","overflow":"hidden","background":"var(--neutralBg)","color":"var(--ink)"},
  calRing: {"position":"absolute","inset":0,"border":"2px solid var(--ink)","borderRadius":8,"zIndex":3,"pointerEvents":"none"},
  calExamRing: {"position":"absolute","inset":0,"border":"2px solid var(--redStrong)","borderRadius":8,"zIndex":2,"pointerEvents":"none"},
  dayDetail: {"background":"var(--panel2)","border":"1px solid var(--line)","borderRadius":9,"padding":"12px 14px","marginBottom":16},
  homeworkInput: {"flex":"1 1 160px","padding":"7px 10px","border":"1px solid var(--line)","borderRadius":8,"fontSize":12.5,"background":"var(--panel2)"},
  homeworkMinutesInput: {"width":46,"padding":"4px 5px","border":"1px solid var(--line)","borderRadius":8,"fontSize":12,"background":"var(--panel2)"},
  reminderSelect: {"padding":"2px 4px","border":"1px solid var(--line)","borderRadius":8,"fontSize":11.5,"background":"var(--panel2)"},
  reminderDaysInput: {"width":40,"padding":"2px 4px","border":"1px solid var(--line)","borderRadius":8,"fontSize":11.5,"background":"var(--panel2)"},
  hwBanner: {"display":"flex","alignItems":"stretch","gap":12,"background":"var(--warmBg)","border":"1px solid var(--gold)","borderLeft":"5px solid var(--gold)","borderRadius":10,"padding":"12px 14px","marginBottom":16},
  textInput: {"flex":"1 1 200px","padding":"8px 10px","border":"1px solid var(--line)","borderRadius":8,"fontSize":13.5,"background":"var(--panel2)"},
  themeBtn: {"border":"1px solid","borderRadius":8,"padding":"6px 14px","fontSize":13,"fontWeight":600},
  syncBtn: {"border":"1px solid var(--line)","background":"var(--panel2)","borderRadius":8,"padding":"5px 10px","fontSize":12.5,"color":"var(--ink)"},
  backupTextarea: {"width":"100%","minHeight":90,"padding":"8px 10px","border":"1px solid var(--line)","borderRadius":9,"fontSize":11.5,"fontFamily":"monospace","background":"var(--panel2)","resize":"vertical","boxSizing":"border-box"},
};
